resources:
  - files-persistentvolumeclaim.yaml
  - mariadb-deployment.yaml
  - mysql-persistentvolumeclaim.yaml
  - owncloud-deployment.yaml
  - owncloud-service.yaml
  - redis-deployment.yaml
  - redis-persistentvolumeclaim.yaml
