apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: mariadb
  name: mariadb
spec:
  ports:
    - name: service-mariadb
      port: 3306
      targetPort: 3306
  selector:
    appservice: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appservice: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      appservice: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        net/default: "true"
        appservice: mariadb
    spec:
      containers:
        - args:
            - --max-allowed-packet=128M
            - --innodb-log-file-size=64M
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MYSQL_DATABASE
              value: owncloud
            - name: MYSQL_PASSWORD
              value: owncloud
            - name: MYSQL_ROOT_PASSWORD
              value: owncloud
            - name: MYSQL_USER
              value: owncloud
          image: mariadb:10.11
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -u
                - root
                - --password=owncloud
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: owncloud-mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      restartPolicy: Always
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
