apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kubernetes.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kubernetes.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kubernetes.network/owncloud-kubernetes-default: "true"
        io.kubernetes.service: mariadb
    spec:
      containers:
        - args:
            - --max-allowed-packet=128M
            - --innodb-log-file-size=64M
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MYSQL_DATABASE
              value: owncloud
            - name: MYSQL_PASSWORD
              value: owncloud
            - name: MYSQL_ROOT_PASSWORD
              value: owncloud
            - name: MYSQL_USER
              value: owncloud
          image: mariadb:10.11
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -u
                - root
                - --password=owncloud
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: owncloud-mariadb
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      restartPolicy: Always
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
status: {}
