apiVersion: v1
kind: Service
metadata:
  name: owncloud-mysql
  labels:
    app: owncloud
spec:
  ports:
    - port: 3306
  selector:
    app: owncloud
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud-mysql
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.11
        name: mysql
        env:
        - name: MARIADB_AUTO_UPGRADE
          value: "1"
        - name: MYSQL_DATABASE
          value: owncloud
        - name: MYSQL_PASSWORD
          value: owncloud
        - name: MYSQL_ROOT_PASSWORD
          value: owncloud
        - name: MYSQL_USER
          value: owncloud
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql-pv-claim

