apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  ports:
    - port: 80
  selector:
    app: owncloud
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-pv-claim
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: frontend
    spec:
      containers:
      - image: 'owncloud/server:10.13'
        name: owncloud
        env:
            - name: OWNCLOUD_ADMIN_PASSWORD
              value: admin
            - name: OWNCLOUD_ADMIN_USERNAME
              value: admin
            - name: OWNCLOUD_DB_HOST
              value: mariadb
            - name: OWNCLOUD_DB_NAME
              value: owncloud
            - name: OWNCLOUD_DB_PASSWORD
              value: owncloud
            - name: OWNCLOUD_DB_TYPE
              value: mysql
            - name: OWNCLOUD_DB_USERNAME
              value: owncloud
            - name: OWNCLOUD_DOMAIN
              value: localhost:8080
            - name: OWNCLOUD_MYSQL_UTF8MB4
              value: "true"
            - name: OWNCLOUD_REDIS_ENABLED
              value: "true"
            - name: OWNCLOUD_REDIS_HOST
              value: redis
            - name: OWNCLOUD_TRUSTED_DOMAINS
              value: localhost
        ports:
        - containerPort: 80
          name: owncloud
        volumeMounts:
            - mountPath: /mnt/data
              name: files
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: oc-pv-claim

