apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kubernetes.service: owncloud
  name: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kubernetes.service: owncloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kubernetes.network/owncloud-kubernetes-default: "true"
        io.kubernetes.service: owncloud
    spec:
      containers:
        - env:
            - name: OWNCLOUD_ADMIN_PASSWORD
              value: admin
            - name: OWNCLOUD_ADMIN_USERNAME
              value: admin
            - name: OWNCLOUD_DB_HOST
              value: mariadb
            - name: OWNCLOUD_DB_NAME
              value: owncloud
            - name: OWNCLOUD_DB_PASSWORD
              value: owncloud
            - name: OWNCLOUD_DB_TYPE
              value: mysql
            - name: OWNCLOUD_DB_USERNAME
              value: owncloud
            - name: OWNCLOUD_DOMAIN
              value: localhost:8080
            - name: OWNCLOUD_MYSQL_UTF8MB4
              value: "true"
            - name: OWNCLOUD_REDIS_ENABLED
              value: "true"
            - name: OWNCLOUD_REDIS_HOST
              value: redis
            - name: OWNCLOUD_TRUSTED_DOMAINS
              value: localhost
          image: 'owncloud/server:10.13'
          livenessProbe:
            exec:
              command:
                - /usr/bin/healthcheck
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: owncloud-server
          ports:
            - containerPort: 8080
              name: http
          resources: {}
          volumeMounts:
            - mountPath: /mnt/data
              name: files
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: files
status: {}
