apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: owncloud
  name: owncloud
spec:
  ports:
    - name: service-owncloud
      port: 8080
      targetPort: 8080
  selector:
    appservice: owncloud
  type: LoadBalancer
