apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kubernetes.service: redis
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}