# Default values for owncloud.

replicaCount: 1


owncloud:
  replicas: 1
  selector:
    matchLabels:
      appservice: owncloud
  strategy:
    type: Recreate
  containers:
    env:
      AdminPass:
        name: OWNCLOUD_ADMIN_PASSWORD
        value: admin
      AdminUser:
        name: OWNCLOUD_ADMIN_USERNAME
        value: admin
      DbHost:
        name: OWNCLOUD_DB_HOST
        value: mariadb
      DbName:
        name: OWNCLOUD_DB_NAME
        value: owncloud
      DbPass:
        name: OWNCLOUD_DB_PASSWORD
        value: owncloud
      DbType:
        name: OWNCLOUD_DB_TYPE
        value: mysql
      DbUser:
        name: OWNCLOUD_DB_USERNAME
        value: owncloud
      DbDomain:
        name: OWNCLOUD_DOMAIN
        value: localhost:8080
      MySqlUtf:
        name: OWNCLOUD_MYSQL_UTF8MB4
        value: "true"
      RedisEn:
        name: OWNCLOUD_REDIS_ENABLED
        value: "true"
      RedisHost:
        name: OWNCLOUD_REDIS_HOST
        value: redis
      TrustedDomains:
        name: OWNCLOUD_TRUSTED_DOMAINS
        value: localhost
    image:
      repository: owncloud/server
      version: "10.13"
      pullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      periodSeconds: 30
      timeoutSeconds: 10
    name: owncloud-server
    ports:
      containerPort: 8080
      protocol: TCP
    volumeMounts:
      mountPath: /mnt/data
      name: files
  restartPolicy: Always
  volumes:
    name: files
    persistentVolumeClaim:
      claimName: files
      storage: 100Mi
  service:
    ports:
      name: service-owncloud
      port: 8080
      targetPort: 8080
    type: LoadBalancer

mariaDb:
  containers:
    env:
      autoUpgrade:
        name: MARIADB_AUTO_UPGRADE
        value: "1"
      mySql:
        db:
          name: MYSQL_DATABASE
          value: owncloud
        pass:
          name: MYSQL_PASSWORD
          value: owncloud
        rootPass:
          name: MYSQL_ROOT_PASSWORD
          value: owncloud
        user:
          name: MYSQL_USER
          value: owncloud
    image:
      repository: mariadb
      version: "10.11"
    name: owncloud-mariadb
    volumeMounts:
      mountPath: /var/lib/mysql
      name: mysql
    livenessProbe:
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5
  restartPolicy: Always
  replicas: 1
  strategy:
    type: Recreate
  volumes:
    name: mysql
    persistentVolumeClaim:
      claimName: mysql
      storage: 100Mi
  service:
    ports:
      name: service-mariadb
      port: 3306
      targetPort: 3306

redis:
  name: redis
  containers:
    name: owncloud-redis
    volumeMounts:
      mountPath: /data
      name: redis
    replicas: 1
    image:
      repository: redis
      version: "6"
    livenessProbe:
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 5
  restartPolicy: Always
  volumes:
    name: redis
    persistentVolumeClaim:
      claimName: redis
      storage: 100Mi
  service:
    ports:
      name: service-redis
      port: 6379
      targetPort: 6379
