apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: mariadb
  name: mariadb
spec:
  ports:
    - name: service-mariadb
      port: 3306
      targetPort: 3306
  selector:
    appservice: mariadb