apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: mariadb
  name: mariadb
spec:
  ports:
    - name: {{ .Values.mariaDb.service.ports.name }}
      port: {{ .Values.mariaDb.service.ports.port }}
      targetPort: {{ .Values.mariaDb.service.ports.targetPort }}
  selector:
    appservice: mariadb