apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appservice: mysql
  name: {{ .Values.mariaDb.volumes.persistentVolumeClaim.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariaDb.volumes.persistentVolumeClaim.storage }}
