apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kubernetes.service: mysql
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
