apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: owncloud
  name: owncloud
spec:
  ports:
    - name: {{ .Values.owncloud.service.ports.name }}
      port: {{ .Values.owncloud.service.ports.port }}
      targetPort: {{ .Values.owncloud.service.ports.targetPort }}
  selector:
    appservice: owncloud
  type: {{ .Values.owncloud.service.type }}
