apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appservice: owncloud
  name: owncloud
spec:
  replicas: {{ .Values.owncloud.replicas }}
  selector:
    matchLabels:
      appservice: owncloud
  strategy:
    type: {{ .Values.owncloud.strategy.type }}
  template:
    metadata:
      labels:
        net/default: "true"
        appservice: owncloud
    spec:
      containers:
        - env:
            - name: {{ .Values.owncloud.containers.env.AdminPass.name }}
              value: {{ .Values.owncloud.containers.env.AdminPass.value }}
            - name: {{ .Values.owncloud.containers.env.AdminUser.name }}
              value: {{ .Values.owncloud.containers.env.AdminUser.value }}
            - name: {{ .Values.owncloud.containers.env.DbHost.name }}
              value: {{ .Values.owncloud.containers.env.DbHost.value }}
            - name: {{ .Values.owncloud.containers.env.DbName.name }}
              value: {{ .Values.owncloud.containers.env.DbName.value }}
            - name: {{ .Values.owncloud.containers.env.DbPass.name }}
              value: {{ .Values.owncloud.containers.env.DbPass.value }}
            - name: {{ .Values.owncloud.containers.env.DbType.name }}
              value: {{ .Values.owncloud.containers.env.DbType.value }}
            - name: {{ .Values.owncloud.containers.env.DbUser.name }}
              value: {{ .Values.owncloud.containers.env.DbUser.value }}
            - name: {{ .Values.owncloud.containers.env.MySqlUtf.name }}
              value: "true"
            - name: {{ .Values.owncloud.containers.env.RedisEn.name }}
              value: "true"
            - name: {{ .Values.owncloud.containers.env.RedisHost.name }}
              value: {{ .Values.owncloud.containers.env.RedisHost.value }}
            - name: {{ .Values.owncloud.containers.env.TrustedDomains.name }}
              value: {{ .Values.owncloud.containers.env.TrustedDomains.value }}
          image: {{ .Values.owncloud.containers.image.repository }}:{{ .Values.owncloud.containers.image.version }}
          livenessProbe:
            exec:
              command:
                - /usr/bin/healthcheck
            failureThreshold: {{ .Values.owncloud.containers.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.owncloud.containers.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.owncloud.containers.livenessProbe.timeoutSeconds }}
          name: {{ .Values.owncloud.containers.name }}
          ports:
            - containerPort: {{ .Values.owncloud.containers.ports.containerPort }}
              protocol: {{ .Values.owncloud.containers.ports.protocol }}
          volumeMounts:
            - mountPath: {{ .Values.owncloud.containers.volumeMounts.mountPath }}
              name: {{ .Values.owncloud.containers.volumeMounts.name }}
      restartPolicy: {{ .Values.owncloud.restartPolicy }}
      volumes:
        - name: {{ .Values.owncloud.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.owncloud.volumes.persistentVolumeClaim.claimName }}
