apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appservice: redis
  name: {{ .Values.redis.volumes.persistentVolumeClaim.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.volumes.persistentVolumeClaim.storage }}