apiVersion: v1
kind: Service
metadata:
  labels:
    appservice: redis
  name: redis
spec:
  ports:
    - name: {{ .Values.redis.service.ports.name }}
      port: {{ .Values.redis.service.ports.port }}
      targetPort: {{ .Values.redis.service.ports.targetPort }}
  selector:
    appservice: redis