apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appservice: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      appservice: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        net/default: "true"
        appservice: redis
    spec:
      containers:
        - args:
            - --databases
            - "1"
          image: redis:6
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: owncloud-redis
          volumeMounts:
            - mountPath: /data
              name: redis
      restartPolicy: Always
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
